import pandas as pd

from config.paths import data_path


# ---------------- DATA LOADING ---------------- #

def load_data():
    """Load and merge all source CSV files into a single sales dataframe."""

    customers = pd.read_csv(data_path("customers.csv"))
    products = pd.read_csv(data_path("products.csv"))
    invoices = pd.read_csv(data_path("invoices.csv"))
    invoice_details = pd.read_csv(data_path("invoice_details.csv"))

    sales_df = (
        invoice_details
        .merge(invoices, on="invoice_id", validate="many_to_one")
        .merge(customers, on="customer_id", validate="many_to_one")
        .merge(products, on="product_id", validate="many_to_one")
    )

    sales_df["invoice_date"] = pd.to_datetime(
        sales_df["invoice_date"],
        errors="coerce",
    )

    return sales_df


# ---------------- FILTERING ---------------- #

def filter_data(
    sales_df,
    city=None,
    customer=None,
    product=None,
    start_date=None,
    end_date=None,
):
    """Filter sales data by location, customer, product and date."""

    df = sales_df.copy()

    filters = {
        "city": city,
        "customer_name": customer,
        "product_name": product,
    }

    for column, value in filters.items():
        if value:
            df = df[df[column] == value]

    if start_date:
        df = df[df["invoice_date"] >= pd.to_datetime(start_date)]

    if end_date:
        df = df[df["invoice_date"] <= pd.to_datetime(end_date)]

    return df


# ---------------- KPI CALCULATIONS ---------------- #

def get_total_sales(df):
    """Total revenue."""
    return df["total_amount"].sum()


def get_total_invoice_count(df):
    """Number of unique invoices."""
    return df["invoice_id"].nunique()


def get_total_customer_count(df):
    """Number of active customers."""
    return df["customer_id"].nunique()


def get_total_product_count(df):
    """Number of distinct products sold."""
    return df["product_id"].nunique()


def get_total_quantity(df):
    """Total quantity sold."""
    return df["quantity"].sum()


def get_total_city_count(df):
    """Number of cities with sales."""
    return df["city"].nunique()


def get_average_invoice_amount(df):
    """Average invoice amount."""

    invoice_totals = (
        df.groupby("invoice_id")["total_amount"]
        .sum()
    )

    return 0 if invoice_totals.empty else invoice_totals.mean()


# ---------------- CUSTOMER ANALYSIS ---------------- #

def get_customer_sales(df):
    """Revenue by customer."""

    return (
        df.groupby("customer_name")["total_amount"]
        .sum()
        .sort_values(ascending=False)
    )


def get_customer_product_share(
    city_base_df,
    period_df,
    active_filters,
):
    """
    Percentage of the selected customer's revenue
    generated by the selected product.
    """

    customer = active_filters.get("customer")
    product = active_filters.get("product")

    if not customer or not product:
        return 0

    selected_sales = period_df[
        (period_df["customer_name"] == customer)
        & (period_df["product_name"] == product)
    ]["total_amount"].sum()

    full_sales = load_data()

    customer_df = filter_data(
        full_sales,
        city=None if active_filters.get("city") == "Hepsi" else active_filters.get("city"),
        start_date=active_filters.get("start_date"),
        end_date=active_filters.get("end_date"),
    )

    customer_total = customer_df[
        customer_df["customer_name"] == customer
    ]["total_amount"].sum()

    if customer_total == 0:
        return 0

    return (selected_sales / customer_total) * 100


def get_product_customer_share(
    period_df,
    active_filters,
):
    """
    Percentage of the selected product's revenue
    generated by the selected customer.
    """

    customer = active_filters.get("customer")
    product = active_filters.get("product")

    if not customer or not product:
        return 0

    selected_sales = period_df[
        (period_df["customer_name"] == customer)
        & (period_df["product_name"] == product)
    ]["total_amount"].sum()

    full_sales = load_data()

    product_df = filter_data(
        full_sales,
        start_date=active_filters.get("start_date"),
        end_date=active_filters.get("end_date"),
    )

    product_total = product_df[
        product_df["product_name"] == product
    ]["total_amount"].sum()

    if product_total == 0:
        return 0

    return (selected_sales / product_total) * 100


# ---------------- PRODUCT ANALYSIS ---------------- #

def get_product_sales(df):
    """Revenue by product."""

    return (
        df.groupby("product_name")["total_amount"]
        .sum()
        .sort_values(ascending=False)
    )


# ---------------- TIME SERIES ---------------- #

def get_monthly_sales(df):
    """Monthly revenue."""

    monthly = df.copy()
    monthly["year_month"] = monthly["invoice_date"].dt.to_period("M").astype(str)

    return (
        monthly.groupby("year_month")["total_amount"]
        .sum()
    )


def get_monthly_quantity(df):
    """Monthly quantity sold."""

    monthly = df.copy()
    monthly["year_month"] = monthly["invoice_date"].dt.to_period("M").astype(str)

    return (
        monthly.groupby("year_month")["quantity"]
        .sum()
    )
